// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfVgyDHvNTUxt5__EBKsCbqozDkZeVI-I',
    appId: '1:829605890857:web:ed207a3f1eef89043e0538',
    messagingSenderId: '829605890857',
    projectId: 'olx-1-d68b6',
    authDomain: 'olx-1-d68b6.firebaseapp.com',
    databaseURL: 'https://olx-1-d68b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olx-1-d68b6.appspot.com',
    measurementId: 'G-EYXDEW1YNT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHGT1Gj-yokc8O1sZoQ5kHH2J10jo00W0',
    appId: '1:829605890857:android:6dd6b2f0523f54ad3e0538',
    messagingSenderId: '829605890857',
    projectId: 'olx-1-d68b6',
    databaseURL: 'https://olx-1-d68b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olx-1-d68b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc4zToLuE9zs2XoBsoNSLWqDmP4VXt7P0',
    appId: '1:829605890857:ios:33eb09482026a26d3e0538',
    messagingSenderId: '829605890857',
    projectId: 'olx-1-d68b6',
    databaseURL: 'https://olx-1-d68b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olx-1-d68b6.appspot.com',
    iosClientId: '829605890857-7dgbl9d3nbcav16bho6uh7e7kt031v8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc4zToLuE9zs2XoBsoNSLWqDmP4VXt7P0',
    appId: '1:829605890857:ios:33eb09482026a26d3e0538',
    messagingSenderId: '829605890857',
    projectId: 'olx-1-d68b6',
    databaseURL: 'https://olx-1-d68b6-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'olx-1-d68b6.appspot.com',
    iosClientId: '829605890857-7dgbl9d3nbcav16bho6uh7e7kt031v8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
