// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO0cGyTLZdulZjCvxMLchFuvl0DnUQ_-c',
    appId: '1:979319833074:web:37ebda44fded14f06aab6b',
    messagingSenderId: '979319833074',
    projectId: 'studenthelperolx',
    authDomain: 'studenthelperolx.firebaseapp.com',
    storageBucket: 'studenthelperolx.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKj3tZyD2hWheahG4iiP4mAiOSBmzb0cM',
    appId: '1:979319833074:android:5954303df95721826aab6b',
    messagingSenderId: '979319833074',
    projectId: 'studenthelperolx',
    storageBucket: 'studenthelperolx.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJbi2yCYEiyVJx4gTtSrXfAtplq0oH8UM',
    appId: '1:979319833074:ios:52c14615401709546aab6b',
    messagingSenderId: '979319833074',
    projectId: 'studenthelperolx',
    storageBucket: 'studenthelperolx.appspot.com',
    iosClientId: '979319833074-8gf76j4qf8ih8o7ofbkaptqj0qhm0ocu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJbi2yCYEiyVJx4gTtSrXfAtplq0oH8UM',
    appId: '1:979319833074:ios:52c14615401709546aab6b',
    messagingSenderId: '979319833074',
    projectId: 'studenthelperolx',
    storageBucket: 'studenthelperolx.appspot.com',
    iosClientId: '979319833074-8gf76j4qf8ih8o7ofbkaptqj0qhm0ocu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
